### ISSUE TITLE
Api method "isJoiSchema" before validation

### ISSUE THREAD

**Issue by stepanzabelin** [joiful-ts/joiful#105]
Hi. I use your lib, thank you!
I'm having some difficulties
I use GlobalPipes (NEST.JS) which  checks all entry data

`app.useGlobalPipes(new JoiValidationPipe());`

But sometimes i don't need to use DTO
![image](https://user-images.githubusercontent.com/45755031/75038601-bb8c9880-54c7-11ea-8769-4a91fe2bee2b.png)

I had to write the following code  to not get mistakes in JoiValidationPipe

![image](https://user-images.githubusercontent.com/45755031/75038861-5f764400-54c8-11ea-9093-6b059a5ad381.png)

Can we have method 
`jf.isJoiSchema(value, metatype)`
for checking before validation ?

**Comment by laurence-myers** [comment]
Great idea! I thought `joiful` had this already, but it seems not.

A couple of comments:
- `tsdv:working-schema` is an implementation detail, and might not exist once the class's full schema is compiled and stored in the metadata `tsdv:schema`. (@codeandcats, should we rename the metadata keys from `tsdv:*` to `joiful:*`?)
- joiful has a `getWorkingSchema()` function, which might be able to replace your boolean expression, but I don't think that function is exported from joiful.

Please feel free to submit a PR to add this functionality! 🙂

**Comment by codeandcats** [comment]
@stepanzabelin I'm curious, what happens if you don't check if there is a schema associated with the class (i.e. just remove the one line with `hasMetadata`)? I'd have expected Joiful to simply say the input is valid and not do a transform.

**Comment by stepanzabelin** [comment]
@codeandcats 
if i remove `hasMetadata` I get joi validation error 
[ValidationError]: "update_id" is not allowed. "message" is not allowed
in this case "update_id" and  "message" are keys of entry object
![image](https://user-images.githubusercontent.com/45755031/75233207-8cc53980-57c9-11ea-872a-f750f333acbb.png)

I guess that a joi parameter  `.unknown(true)` is needed somewhere in the source code 

@laurence-myers thank you . I'll try to submit a PR

**Comment by codeandcats** [comment]
@stepanzabelin Ah I understand. Sorry I didn't think about the case of disallowed unknown keys. That makes sense.

@laurence-myers I would suggest we expose a function that works similar to [`getJoiSchema`](https://github.com/joiful-ts/joiful/blob/a897068377c0889b3e0949f8acbaa80347d160a6/src/core.ts#L91) but does not create an empty schema if there are no schemas defined in the metadata for the given class or any of the ancestor classes up the prototype chain. What do you think?

**Comment by stepanzabelin** [comment]
I looked up at the code. Method "validateAsClass" has third argument, that takes Joi options.
so i can pass `{allowUnknown:true}` 


```const {error, value: transformedValue} = jf.validateAsClass(value, metatype, {allowUnknown:true});```

Unfortunately it is not in the lib documentation.
it partially solves my problem, but anyway i need to check if there is joi schema
