### ISSUE TITLE
@string().allow not working

### ISSUE THREAD

**Issue by fider-apptimia** [joiful-ts/joiful#126]
**@string().allow() pass unallowed strings.**

Env:
- Node.js v12.14.1
- joiful@2.0.0
- ts-node@8.8.2
- typescript@3.8.3

Compiler options:
```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "noImplicitAny": true,
    "module": "CommonJS",
    "moduleResolution": "node",
    "allowJs": true,
    "strict": true,
    "isolatedModules": true,
    "pretty": true,
    "sourceMap": true,
    "target": "es2018",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "rootDir": "./",
    "outDir": "./dist"
  },
  "exclude": ["dist", "node_modules"]
}
```

Reproduce:
```js
import * as jf from 'joiful';

class C {
  @jf.string().allow('a', 'b').required()
  ab!: string;
}

const c = new C();
c.ab= 'x';

// expected error != null
console.dir(jf.validateAsClass(c, C));
// {
//  error: null,
//  value: C { ab: 'x' },
//  then: [Function: then],
//  catch: [Function: catch]
//}
```

**Comment by laurence-myers** [comment]
Looks like `allow()` is for allowing specific values _in addition_  to the rest of the schema. So you could have a `number()` schema that also accepts the string `"NaN"`.

https://github.com/hapijs/joi/blob/master/API.md#anyallowvalues

> Note that this list of allowed values is in addition to any other permitted values. To create an exclusive list of values, see any.valid(value).

Try `valid()` instead, see if that works.

https://github.com/hapijs/joi/blob/master/API.md#anyvalidvalues---aliases-equal

**Comment by fider-apptimia** [comment]
Thanks
