### ISSUE TITLE
Number validation fail when passing string number ('10')

### ISSUE THREAD

**Issue by jdjmartinez** [joiful-ts/joiful#140]
This is the code:

![image](https://user-images.githubusercontent.com/62573136/84810296-c6b48880-afd0-11ea-819c-85810ab30f7b.png)

The log of result: 
Error is null and should fail because number is an string
![image](https://user-images.githubusercontent.com/62573136/84810393-e946a180-afd0-11ea-9046-f0bb5a3b4801.png)

**Comment by laurence-myers** [comment]
This is a feature of `joi`. It will attempt to coerce e.g. strings to numbers, if the string contains a valid number. You can disable it by passing the option `convert: false` to the `joiful` validation methods.

> convert - when true, attempts to cast values to the required types (e.g. a string to a number). Defaults to true.

https://hapi.dev/module/joi/api/?v=17.1.1#anyvalidatevalue-options

**Comment by laurence-myers** [comment]
@jdjmartinez I hope I answered your question, I'll close this issue, but feel free to reach out if you have further questions.
