### ISSUE TITLE
Fluent API for decorators

### ISSUE THREAD

**Issue by codeandcats** [joiful-ts/joiful#15]
I've been using the library a fair bit lately and I've started thinking it would be nice to support a fluent API.

So instead of this:

```typescript
export class FormFields {
  @Required()
  @Min(1)
  @Label('First Name')
  @StringSchema()
  firstName: string;

  @Required()
  @Min(1)
  @Label('Last Name')
  @StringSchema()
  lastName: string;

  @Required()
  @Label('E-mail Address')
  @Email()
  @StringSchema()
  emailAddress: string;

  @Required()
  @Label('Age')
  @Min(18)
  @NumberSchema()
  age: number;
}
```

You could use:

```typescript
export class FormFields {
  @StringSchema().label('First Name').min(1).required()
  firstName: string;

  @StringSchema().label('lastName').min(1).required()
  lastName: string;

  @StringSchema().label('E-mail Address').email().required()
  emailAddress: string;

  @NumberSchema().label('Age').min(18).required()
  age: number;
}
```

## Motivation

Admittedly, at first it looks not too dissimilar from simply removing the line-breaks from the individual decorators, but it does have a couple advantages.

1. When simply typing in a constraint like `Min` and allowing the IDE/plugin to automatically add the import statement for you, you have to be careful that it imports from the correct constraint directory (string, number, date, array, object). By using a fluent API you'd always get the right min function.

2. A fluent would also limit the validation constraints you have available for your chosen schema type, this way you can't accidentally include constraint decorators that make no sense for your type, which can easily happen when copying and pasting.

3. It also makes the API a little more discoverable. You don't have to hunt through the `.d.ts` files of `tsdv-joi` to find the right name of the decorator you need. You just start with the type e.g. `@StringSchema()` hit dot and you immediately see the constraints you have available for that type.

4. I've also noticed some constraints error at runtime if the schema type is not immediately declared before (i.e. below) the constraint in question. I don't remember which ones did this now but I try to remember to always declare the schema type immediately above the property. This is not obvious to a new user though and an easy mistake to make. A fluent API would avoid this.

Anyway, was just a thought. There are probably other ways to address this issues too which may require less work.

**Comment by laurence-myers** [comment]
Sounds good. Could it support custom constraints?

If you have duplicated similar constraints on multiple properties, I recommend writing a custom wrapper decorator.

Some other notes:
- You only need to supply the schema decorator if tsdv-joi can't infer the property type from the class metadata. This usually happens when you use union or intersection types, since there's no equivalent constructor type (which is how metadata provides runtime info on the type) E.g. `number` becomes `Number`, but `number | null` becomes ??? (I don't recall off-hand)
- You could omit `Optional()` or `Required()` depending on how you configure the validator instance. I think it's optional by default.
- You can import e.g. `StringConstraints` and uae your editor's autocomplete to see what's available. This has the advantage of allowing you to mix decorators with the same name, e.g. `NumberConstraints.Max()` vs `StringConstraints.Max()`. You can also refer to the Joi documentation (which I recommend anyway, since I have not written any usage docs for tsdv-joi), and just capitalise each methid name to work out the equivalent decorator.
- Issue #14 could resolve some issues, it would prevent applying decorators to invalid property types.
- Maybe the whole lib could be simplified to a single "Joi()" decorator, since Joi uses a fluent interface. I don't know if there's implications with class inheritance.

Anyway, if this is useful, feel free to raise a PR with tests.

**Comment by codeandcats** [comment]
Thanks for the quick feedback!

> Could it support custom constraints?

By custom constraints do you mean a way of allowing completely custom validation code, like supplying a custom validation function? If so this should be doable. Example for a custom (_very_) naive email validator for illustration: `@Any.custom(value => value.indexOf('@') > -1)` (p.s. I've been meaning to ask you if/how this is currently possible with joi / tsdv-joi).

> You could omit Optional() or Required() depending on how you configure the validator instance. I think it's optional by default.

Cool! I didn't know that. 👍

> You can import e.g. StringConstraints and uae your editor's autocomplete to see what's available. This has the advantage of allowing you to mix decorators with the same name, e.g. NumberConstraints.Max() vs StringConstraints.Max(). You can also refer to the Joi documentation (which I recommend anyway, since I have not written any usage docs for tsdv-joi), and just capitalise each methid name to work out the equivalent decorator.

Good point, that's true. Though it does make things a little more verbose.

```typescript
export class FormFields {
  @StringContraints.Min(1)
  @AnyConstraints.Label('First Name')
  firstName: string;

  @StringConstraints.Min(1)
  @AnyConstraints.Label('Last Name')
  lastName: string;

  @AnyConstraints.Label('E-mail Address')
  @StringConstraints.Email()
  emailAddress: string;

  @AnyConstraints.Label('Age')
  @NumberConstraints.Min(18)
  age: number;
}
```

> Issue #14 could resolve some issues, it would prevent applying decorators to invalid property types.

Agree, looking forward to it! 👍

> Maybe the whole lib could be simplified to a single "Joi()" decorator, since Joi uses a fluent interface. I don't know if there's implications with class inheritance.

Yeah I quite like this idea. It would make tsdv-joi an even closer match syntax wise to joi for easier adoption and allow for a pretty terse syntax.

Unless you'd like to have a go at this yourself, I can create a feature branch and have a bit of a play to see how easy this is to implement and whether the value is worth it.

**Comment by laurence-myers** [comment]
> By custom constraints do you mean a way of allowing completely custom validation code, like supplying a custom validation function? If so this should be doable. Example for a custom (_very_) naive email validator for illustration: `@Any.custom(value => value.indexOf('@') > -1)` (p.s. I've been meaning to ask you if/how this is currently possible with joi / tsdv-joi).

Joi supports [custom validation by "extending" Joi](https://github.com/hapijs/joi/blob/v10.6.0/API.md#extendextension). It's not ideal for use with tsdv-joi:

- Extended Joi returns a new instance of Joi, the base library is unchanged. This means decorators need a way to pass in the Joi instance. Currently, tsdv-joi allows this via the `registerJoi()` function, but I haven't actually tested this. It also means the Joi instance is applied globally across tsdv-joi; you can't have decorator A using Joi instance A, and decorator B using Joi instance B. (But I don't think it's a big issue, unless you have app A using tsdv-joi, and it imports dependency B which also uses tsdv-joi, and both use their own extended instance of Joi... *sigh*)
- Type safety becomes problematic. If you extend Joi, you also have to remember to use declaration merging to extend Joi's types to include the new rule as a method on the appropriate Joi schema. But I don't know if tsdv-joi will play nice with any augmented types.

> Unless you'd like to have a go at this yourself, I can create a feature branch and have a bit of a play to see how easy this is to implement and whether the value is worth it.

Please do! 🙂

It might be worth having once generic decorator for applying any schema, and also modifying the `StringSchema`, `AnySchema` etc decorators to take an optional function, which applies type-specific decorators. E.g.

```typescript
@StringConstraints.StringSchema((schema: Joi.StringSchema) => schema.trim().uppercase().length(10))
```
