### ISSUE TITLE
Move to new joi package

### ISSUE THREAD

**Issue by bl4ckb0ne** [joiful-ts/joiful#163]
I saw that the package [`@hapi/joi`][1] is now deprecated, in favour of the new [`joi`][2] package. Is a move to the new packaged planned or already in the work?

[1]: https://www.npmjs.com/package/@hapi/joi
[2]: https://www.npmjs.com/package/joi

**Comment by laurence-myers** [comment]
We're a few versions behind `joi`/`@hapi/joi`. I don't think anyone is currently looking at doing the upgrade. A PR would be welcome! 🙂

Are there particular features or changes from the newer version(s) of `joi` that you need?

**Comment by bl4ckb0ne** [comment]
I was just messing aroung trying to use `joiful` with deno through [skypack.dev](https://www.skypack.dev/) and hit this issue since the `@hapi/joi` package does not exist there.

I have already started the patch and hit a few issues with `joi`, I think their types file are missing a few things (like [Schema](https://github.com/sideway/joi/blob/master/lib/index.d.ts#L10), and some things have changed in the API. I'll see with my work if I can get some time to fix that.

**Comment by bl4ckb0ne** [comment]
I made a [draft](https://github.com/joiful-ts/joiful/pull/166) for the move from 15 to 16, i plan on finishing the move from 16 to 17 this week, and then move to [sideway/joi](https://github.com/sideway/joi) for 17.3.0
