### ISSUE TITLE
Error at script startup: "Cannot find module 'reflect-metadata'"

### ISSUE THREAD

**Issue by victorbadila** [joiful-ts/joiful#164]
I have updated `tsconfig` as per documentation and when I built my app it was build with `tsc --experimentalDecorators`. However when trying to run the resulting js I get the following  error:

```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'reflect-metadata'
Require stack:
- C:\myapp\node_modules\joiful\core.js
- C:\myapp\node_modules\joiful\decorators\common.js
- C:\myapp\node_modules\joiful\decorators\any.js
- C:\myapp\node_modules\joiful\joiful.js
- C:\myapp\node_modules\joiful\index.js
- C:\myapp\dist\features\checkout-cart\stuff.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
```

**Comment by codeandcats** [comment]
Hi @victorbadila, you will need to import `reflect-metadata` (ideally as the first import in your app) when working with any TS project that emits decorator metadata. You can add it from npm.

**Comment by victorbadila** [comment]
It worked, thanks @codeandcats

**Comment by ujwal-setlur** [comment]
``reflect-metadata`` should be in ``dependencies`` section of ``package.json`` vs ``devDependencies``. ``reflect-metadata`` is imported in ``src/core.ts`` which makes it a direct dependency. This will break the build of any project that depends on ``joiful``, but otherwise does not depend on ``reflect-metadata``.
