### ISSUE TITLE
Conventional commits

### ISSUE THREAD

**Issue by codeandcats** [joiful-ts/joiful#17]
I recommend using a couple libraries to help manage versioning and change logs better.

- [commitlint](https://www.npmjs.com/package/@commitlint/cli). Used to ensure commit messages conform to a standard convention
- Something like [husky](https://www.npmjs.com/package/husky) to handle the `commit-msg` git hook and trigger validation using commitlint. Husky is a single library you can use to handle precommit events too.
- [commitlint/prompt-cli](https://www.npmjs.com/package/@commitlint/prompt-cli) - CLI to use in place of `git commit` (e.g. `npm run commit`) that prompts your for the type, scope, message and optional body and footer for your commit. Not essential if you are familiar with the commit message convention but I like it.
- [standard-version](https://www.npmjs.com/package/standard-version). Used when you're ready to create a release. It will:
  1. Parse the previous commit messages
  2. Add your messages to `CHANGELOG.md`
  3. Bump the package version by either a patch, minor or major version depending on your commit messages. i.e. a commit including the words "BREAKING CHANGES" will increment the major version, otherwise a commit type of `feat` will increment the minor version, otherwise only the patch is incremented.
  4. Commit.
  5. Add a release tag.

When you're ready to ship your release you can push your changes to github (including tags) and publish to npm.

I was put onto this technique by someone at my previous job. It seems to be used in a few big libraries. Anyway, I have since adopted it in a few libs as I think it makes a lot of sense and I'm happy to report has been working well. I'd be happy to create a PR if you're at all interested.

**Comment by laurence-myers** [comment]
Thanks for the suggestions. I don't wont to make this project too formal at this time, but using a standard format for commits could be nice, particularly if it helps generate changelogs/release notes.

I use a GUI client for Git, so the `prompt-cli` would probably be wasted on me.

I'm always sceptical about semantic versioning, since even a bug fix could be a breaking change if some consuming application has implemented a workaround or other code based on that bug.

**Comment by codeandcats** [comment]
Now that we're at `1.0.0` I'd like to prioritise this to ensure:

- well formatted commit messages
- automatically generated change log
- automatic semantic version bumping

So I'll probably make this the very next thing I work on.
