### ISSUE TITLE
Find a new name for this project

### ISSUE THREAD

**Issue by laurence-myers** [joiful-ts/joiful#20]
`tsdv-joi` is not memorable, nor does it roll off the tongue. Let's rename the library, and go with the obvious option ~`joi-decorators`~ (seems it's already taken, let's find a new name).

- [x] Rename code & doc references
- [x] Rename the GitHub repository
- [ ] Publish a deprecation notice to npm

**Comment by codeandcats** [comment]
Unfortunately it looks like `joi-decorators` is [already taken on npm](https://www.npmjs.com/package/joi-decorators). 😞

Here's a couple suggestions that are available:
- `decorated-joi`
- `joi-decorated`
- `joi-decor`
- `joiful-decoration`

I kind of like `joi-decor`, it's admittedly a little less explicit, but to me it's a little punny and playful.

**Comment by codeandcats** [comment]
Do any of these names float your goat @laurence-myers, or do you have any other names you like?

**Comment by codeandcats** [comment]
I was thinking how about simply calling the library: _fun_

### Pros:
- It's terse
- It's related to joy
- It's memorable
- It's surprisingly (or maybe not?) available on npm

### Cons:
- Not self-descriptive

The not-being self-descriptive isn't great but maybe it's not the worst thing ever since there are many libraries that also have names that in no way relate to/describe what they do (e.g. `mocha`, `jest`, `joi`, `gulp`, `grunt`, etc...)

Just a throwing it out there.

**Comment by codeandcats** [comment]
Heya, I'm not sure if this will help in this case, but I made a thing that might help in coming up with a new name. 🙏

[npm-name-finder.com](https://npm-name-finder.com/)

Unfortunately, when searching for `joi` it actually isn't that useful. 🤦‍♂🤷‍♂

**Comment by laurence-myers** [comment]
Thanks for all the suggestions! I'm mulling them over. I try to use boring but descriptive names in libs.

I tried your tool, but it told me a name was available that was actually taken. Maybe because I put a space in it?
![2019-05-25 17_25_40-NPM Name Finder](https://user-images.githubusercontent.com/6336048/58366223-71639000-7f12-11e9-8872-9e8143980ea6.png)
![2019-05-25 17_25_31-npm _ build amazing things](https://user-images.githubusercontent.com/6336048/58366225-74f71700-7f12-11e9-8d98-d885f8f8df27.png)

**Comment by codeandcats** [comment]
Hmm sorry about that. I think for om memory when you put in spaces it searches for 2 variations, e.g. “validation-decorators” and “validationdecorators”. The latter is available and most likely the tool is misreporting it. I’ll look into it tomorrow.

**Comment by yagyesha** [comment]
joiful

**Comment by codeandcats** [comment]
FYI, the above bug with [npm-name-finder.com](https://npm-name-finder.com) has been fixed.

**Comment by laurence-myers** [comment]
I've got ahold of the `joiful` package on npm, based on a recommendation (thank you!). I think we'll go ahead with that name. 😄 

The next step is working out when to migrate to the new name. I'd like to tackle some of the major v1 milestone tasks first:
- #22: make Joi a regular dependency
- #21: update to the latest version of Joi
- #35: class-based decorators for all peer-related validations (Or, And, Nand, Xor, With etc)

**Comment by codeandcats** [comment]
Moved final step "Publish a deprecation notice to npm" for this issue into its own issue (#69).
