### ISSUE TITLE
Update to Joi v15+ (the latest)

### ISSUE THREAD

**Issue by laurence-myers** [joiful-ts/joiful#21]
tsdv-joi requires an old version of Joi and its type definitions, let's update to the latest.

This will introduce breaking changes. For example, Joi removed all "date" functionality from the core library, to remove the dependency on moment, thereby minimising the library footprint and making it easier to package for the browser. For tsdv-joi, this means we'd need a separate project to provide decorators for [joi-date](https://github.com/hapijs/joi-date).

**Comment by fider** [comment]
Just a note, how about using [@hapi/joi](https://www.npmjs.com/package/@hapi/joi) instead [joi](https://www.npmjs.com/package/joi)? It is marked as deprecated and not maintained for over 5 months.
