### ISSUE TITLE
Multiple types on field

### ISSUE THREAD

**Issue by ruangato** [joiful-ts/joiful#216]
In the raw Joi lib it is possible to map a field to multiple types using the following approach:

```js
const alt = Joi.alternatives().try(Joi.number(), Joi.string());
```

In there a way to do this using joiful?

**Comment by laurence-myers** [comment]
I think you can use [Joiful's `custom()` method](https://github.com/joiful-ts/joiful/blob/55113435ba8cace0098eeb8f5cca5d6beca0419f/src/decorators/any.ts#L166). Something like this might work?

```
@jf.custom((Joi) => Joi.alternatives().try(Joi.number(), Joi.string()))
myProperty: number | string;
```

I notice we don't have tests or documentation about the `custom()` method, that's something we should add.

**Comment by ruangato** [comment]
> I think you can use [Joiful's `custom()` method](https://github.com/joiful-ts/joiful/blob/55113435ba8cace0098eeb8f5cca5d6beca0419f/src/decorators/any.ts#L166). Something like this might work?
> 
> ```
> @jf.custom((Joi) => Joi.alternatives().try(Joi.number(), Joi.string()))
> myProperty: number | string;
> ```
> 
> I notice we don't have tests or documentation about the `custom()` method, that's something we should add.

It worked like a charm, thanks a lot!

Regarding the tests, I will try to do something about the `custom()` following the guidelines

**Comment by laurence-myers** [comment]
I'll close this issue since `@jf.custom()` worked.
