### ISSUE TITLE
Switch Joi to Peer Dependency

### ISSUE THREAD

**Issue by dhkatz** [joiful-ts/joiful#228]
I recently ran into an issue with another library that depends on Joi.

Because of  adependency mismatch the following error gets thrown by Joi:

`'Cannot mix different versions of joi schemas'`.

The other library has Joi listed as a peer dependency which I believe is the correct way of handling Joi.

Because this library has a dependency instead, Joiful gets its own version of Joi installed instead of sharing an existing compatible version.

This is an example of the dependency issue caused by not listing Joi as a peer dependency.

```
node_modules
  | - joiful
    | - node_modules
      | - joi
  | - joi-to-swagger
  | - joi
```

**Comment by laurence-myers** [comment]
`joiful` used to list `joi` as a peer dependency. We changed it to a regular dependency in [this commit](https://github.com/joiful-ts/joiful/commit/1314228834e53d0aa062ff77122fbab32b4f7c48#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), when we upgraded from `joi@10` to `@hapi/joi@15`. I don't recall why we changed it from a peer dependency. I think it was to avoid issues where the installed version of Joi had unexpected breaking changes.

If you use `yarn` v1.x _(which I strongly recommend over `npm`)_, you can work around this using [selective dependency resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) in your `package.json`.

```json
  "resolutions": {
    "joi": "17.5.0",
  }
```

_(If there's a mix of dependencies on `joi` and  `@hapi/joi`, you're in trouble... 😬)_

**Comment by dhkatz** [comment]
Switching to yarn and adding the resolution seems to have worked. I should say also that npm does have its own version called overrides. Odd that they (or node) haven't decided on a common name
