### ISSUE TITLE
100% code coverage for constraint decorators

### ISSUE THREAD

**Issue by laurence-myers** [joiful-ts/joiful#23]
All constraint decorators should have unit tests.

**Comment by codeandcats** [comment]
FYI a friend and former colleague @brvenkat mentioned over email he’d be keen to help out, probably on this issue if that’s cool with you @laurence-myers?

I suggested just holding off until the jest PR is merged in.

**Comment by venkatb78** [comment]
Hi @laurence-myers , This is Venkat. After working with @codeandcats in vicinity centres, i just started to enjoy writing unit tests and mocks and would like to build expertise in this area and can help out if needed.

**Comment by laurence-myers** [comment]
Hi Venkat, thanks for offering to help! Please feel free to contribute anything you would like to work on, just raise a PR when you're ready.

I've just merged PR #26, which changes the test runner from Mocha to Jest, so you should be ready to get going. Let me know if you have any questions.

**Comment by codeandcats** [comment]
Once we have 100% test coverage, I'd suggest connecting the repo to something like [coveralls](https://coveralls.io) so we can add a `% coverage` badge in the project readme.
