### ISSUE TITLE
Any way to support Joi `alternatives` statement or conditional in other way?

### ISSUE THREAD

**Issue by zelid** [joiful-ts/joiful#233]
Hello,

I have a need to make some properties mandatory depending on other properties.
For example if country is US or CA than state is mandatory.

Joi has support through  `Joi.alternatives().conditional`
```
const schema = Joi.object({
    type: Joi.number().required().valid(1, 2, 3),
    firstname: Joi.alternatives().conditional('type', { is: 1, then: Joi.string().required() }),
    lastname: Joi.alternatives().conditional('type', { is: 1, then: Joi.string().required() }),
    salary: Joi.alternatives().conditional('type', { is: 2, then: Joi.number().required() }),
    pension: Joi.alternatives().conditional('type', { is: 2, then: Joi.number().required() }),
    credit: Joi.alternatives().conditional('type', { is: 3, then: Joi.number().required() }),
    debit: Joi.alternatives().conditional('type', { is: 3, then: Joi.number().required() }),
}))
```

As I understand such decorator is not available with `Joiful` but what could be suitable way to validate conditions? 
Maybe read schema like `const schema = jf.getSchema(Order)` and extend it somehow with conditions.

Any help with ideas how to use both `Joiful` decorators for simple cases and extend special cases like conditions before performing POST body validation with:

```
const jfValidator = new jf.Validator({ abortEarly: false });
const jfResult = jfValidator.validateArrayAsClass(body, Order);
``` 

Thanks for any ideas and suggestions.

**Comment by laurence-myers** [comment]
Please try [Joiful's `custom` decorator](https://github.com/joiful-ts/joiful/blob/55113435ba8cace0098eeb8f5cca5d6beca0419f/src/decorators/any.ts#L166). This gives you access to the Joi instance, exposing more of the original Joi API.

Rough example:

```typescript
class PersonalAccount {
    @jf.custom((Joi) => Joi.alternatives().conditional('type', { is: 1, then: Joi.string().required() }))
    firstname?: string;
}
```

(This is similar to #216)
