### ISSUE TITLE
"Cannot mix different versions of joi schemas" / Upgrading `joi` / Providing external `Joi` instance

### ISSUE THREAD

**Issue by LeoDupont** [joiful-ts/joiful#236]
Hi!

I'm trying to use `joiful` in combination with `express-validation`, but when I try to provide a `joiful`-made schema to the `validate()` middleware, it throws this error: 
```
Error: Cannot mix different versions of joi schemas
```

Sample code I'm using:
```ts
import { Router } from "express";
import { validate, Joi } from "express-validation";
import * as jf from "joiful";

class BodyExample {
	@jf.string().required()
	exampleKey!: string;
}

const router = Router();

router.post("/test",
	validate({
		body: jf.getSchema(BodyExample),
	}),
	
	(req, res) => {
		res.send("ok");
	}
);
```

I'm using `express-validation@4.1.0`, which uses `joi@17.6.0`.
And `joiful@3.0.2`, which uses `joi@17.3.0`.

Is there any way to upgrade `joiful`'s `joi` dependency?

Or to provide an external `joi` object to `jf`? 
Something like: 
```ts
import { validate, Joi } from "express-validation";
import * as jf from "joiful";

jf.joi = Joi;
```

**Comment by LeoDupont** [comment]
Answering my own question.

I've been able to provide an external `Joi` object to `joiful` using it's constructor:
```ts
import { Joi } from "express-validation";
import { Joiful } from "joiful";

const jf = new Joiful({
	joi: Joi as any, // got a typing error otherwise...
});

class BodyExample {
	@jf.string().required()
	exampleKey!: string;
}

const router = Router();

router.post("/test",
	validate({
		body: jf.getSchema(BodyExample),
	}),
	
	(req, res) => {
		res.send("ok");
	}
);
```

This way, I have no longer an error regarding `joi` versions mismatch.

Notes: 
* According to the [constructor's code](https://github.com/joiful-ts/joiful/blob/f0c977b/src/joiful.ts#L16), it seems that the external `Joi` object must have at least the same major version as the embedded `joiful`'s `joi`.
* I get the following typing error if I don't explicitly type `Joi` as `any` in the constructor's options:
```
Type 'import("c:/.../node_modules/joi/lib/index").Root' is not assignable to type 'import("c:/.../node_modules/joiful/node_modules/joi/lib/index").Root'.
  The types of 'any().alter' are incompatible between these types.
    Type '(targets: Record<string, (schema: AnySchema<any>) => Schema<any>>) => AnySchema<any>' is not assignable to type '(targets: Record<string, SchemaFunction>) => AnySchema'.
      Types of parameters 'targets' and 'targets' are incompatible.
        Type 'Record<string, SchemaFunction>' is not assignable to type 'Record<string, (schema: AnySchema<any>) => Schema<any>>'.
          'string' index signatures are incompatible.
            Type 'SchemaFunction' is not assignable to type '(schema: AnySchema<any>) => Schema<any>'.ts(2322)
```

**Comment by laurence-myers** [comment]
I'm glad you worked out a solution. :)

Yeah, it's a bit of a dilemma for joiful. If we make Joi a peer dependency, we run into type errors when using a newer version of Joi, and can't guarantee that it works without error. If we make Joi a dependency of joiful, we run into the problems you found. 😞
