### ISSUE TITLE
Add Joi documentation as jsdoc comments to constraint decorators

### ISSUE THREAD

**Issue by laurence-myers** [joiful-ts/joiful#24]
All decorators should have jsdoc comments, describing how to use each decorator. This information should be duplicated from the Joi documentation, ideally with examples updated to use decorators*.

* Examples may not be necessary if we have unit tests demonstrating how to use each decorator: see #23.

**Comment by codeandcats** [comment]
FYI: I've been adding JSDoc comments to decorators in each PR that adds tests for constraints. I think it would be worth revisiting this issue once [those PRs](https://github.com/laurence-myers/tsdv-joi/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+tests+constraints) are merged in to see what's left.
