### ISSUE TITLE
How to Validate Array class?

### ISSUE THREAD

**Issue by fider** [joiful-ts/joiful#33]
I expect request body to be an array.
How can I achieve something like this:

```javascript

class ArrayItem {
  @StringSchema()
  something: string;
  ...
}

// Array that can be validated:
const ArrayClass: Array<Arrayitem>= CreateArraySchema( ArrayItem );

```

**Comment by laurence-myers** [comment]
It's not quite what you're asking for, but you can use `@NestedArray()` to validate arrays within a containing schema class.
```typescript
class ArrayItem {
  @StringSchema()
  something: string;
  ...
}

class ContainingSchema {
  @NestedArray()
  items: ArrayItem;
}

const validator = new Validator();
const result = validator.validateAsClass({
  items: [
    {
      something: 'foo'
    },
    {
      something: 'bar'
    }
  ]
}, ContainingSchema);
```

If you don't want to use a wrapping schema, you can call the `validateArrayAsClass()` method on the validator.

```typescript
class ArrayItem {
  @StringSchema()
  something: string;
  ...
}

const validator = new Validator();
const result = validator.validateArrayAsClass({
  items: [
    {
      something: 'foo'
    },
    {
      something: 'bar'
    }
  ]
}, ArrayItem);
```

If you want to automatically validate either an object or an array, you might have to implement your own logic to call the appropriate validator method. Some example code is below.
```typescript
const validationClass = SomeValidationSchemaClass;
const valueToValidate = /* {} or [] */;
if (Array.isArray(valueToValidate)) {
  return validator.validateArrayAsClass(valueToValidate, validationClass);
} else {
  return validator.validateAsClass(valueToValidate, validationClass);
}
```

You could argue that tsdv-joi should automatically decide whether to validate the value as an array if it is an array. But then, you're letting the value decide what validation to use, which seems a bit backwards.

**Comment by laurence-myers** [comment]
I take it this answered your question, please re-open if you have further questions.
