### ISSUE TITLE
Creating isolated instances of tsdv-joi

### ISSUE THREAD

**Issue by codeandcats** [joiful-ts/joiful#41]
Currently the instance of `joi` used by `tsdv-joi` can be overridden by the application developer. However this is currently a global, which means the application could be using a library that also uses `tsdv-joi` and expects different behaviour from the `joi` instance or sets the instance itself.

In order to work better with other libraries, as @laurence-myers suggested, it would be better if consumers could create their own instances of `tsdv-joi` where they could set any specific configurations they need in complete isolation. As well as setting the `joi` instance, this would also be useful for registering a [label provider function](https://github.com/laurence-myers/tsdv-joi/issues/40) in isolation.

Existing exported decorators would continue to work as is with a *default* instance of `tsdv-joi`.

For example:

```typescript
import { TsdvJoi } from 'tsdv-joi';
import * as joi from 'joi';
import * as Case from 'case';

const tsdvJoi = new TsdvJoi({
  joi,
  labelProvider: propertyName => Case.sentence(propertyName)
});
```

**Comment by codeandcats** [comment]
@laurence-myers I feel like this should be part of v1.0.0 too. Sound okay?

I'd be keen to pick this one up unless you want to tackle it?

**Comment by laurence-myers** [comment]
Yes, sounds good. 🙂

**Comment by codeandcats** [comment]
Hey @laurence-myers, I'd like to get your opinion on how to best move forward on this.

Let's say we create an instance of TsdvJoi like so:

```typescript
import { TsdvJoi } from 'tsdv-joi';
import * as joi from 'joi';
import * as Case from 'case';

const tsdvJoi = new TsdvJoi({
  joi,
  labelProvider: propertyName => Case.sentence(propertyName)
});
```

Then to decorate a class we could go with something like this:

```typescript
const { Integer, Positive Required, StringSchema } = tsdvJoi;

class SignUp {
  @Required()
  @StringSchema()
  emailAddress!: EmailAddress;

  @Required()
  password!: string;

  @Required()
  @Positive()
  @Integer()
  age!: Integer;
}
```

However, I'm not sure how to best handle decorators that share the same name for different schema types (e.g. `min`, `max`, etc)

We could put all the decorators under a namespace, but it gets a bit verbose...

```typescript
const { AnyConstraints, NumberConstraints, StringConstraints } = tsdvJoi;

class SignUp {
  @AnyConstraints.Required()
  @StringConstraints.StringSchema()
  emailAddress!: EmailAddress;

  @AnyConstraints.Required()
  @StringConstraints.Min(8)
  password!: string;

  @AnyConstraints.Required()
  @NumberConstraints.Min(18)
  @NumberConstraints.Integer()
  age!: Integer;
}
```

We could keep things shorter if we forget about the namespaces, and only implement Schema decorators and use the fluent API:

```typescript
const { NumberSchema, StringSchema } = tsdvJoi;

class SignUp {
  @StringSchema(s => s.required())
  emailAddress!: EmailAddress;

  @StringSchema(s => s.min(8).required())
  password!: string;

  @NumberSchema(s => s.integer().min(18).required())
  age!: Integer;
}
```

But I feel like if we have decorators for everything else, we shouldn't force the user to use the fluent API when using TsdvJoi instances.

Given the potential for the consumer to be using the API a lot (like for all their business models, DTOs, forms, etc), I think one of our design goals should be to keep the API _as terse as possible_ while still being meaningful. So I was wondering if you'd be open to using the 1.0.0 release to make any breaking changes we think would improve the API. I'm curious, if you had the chance now to start fresh what you would change if anything. 🤔

I was wondering if it might make sense to remove the non-schema based decorators (with the exception of future class-level decorators) and just use the fluent API?

This would:
- Make the API for using instances of TsdvJoi mirror exactly the global instance API while keeping both terse.
- Mean there's less maintenance to support changes to joi (e.g. if they add a `titleCase` constraint for string schemas, we just get it for free without needing to add a decorator for it)
- Greatly reduce the code base, complexity and tests
- Result in one simple, unified API for consumer to learn

This would also:
- Result in breaking changes, forcing consumer to upgrade their app in order to use latest tsdv-joi
- Require existing users to learn new API

I'm keen to hear your thoughts on how you think we should proceed. 😃
