### ISSUE TITLE
Directly importing sub-modules requires "dist" in the path

### ISSUE THREAD

**Issue by laurence-myers** [joiful-ts/joiful#5]
# Problem
JavaScript files are generated into a `dist` directory. The NPM module is packaged to include the whole `dist` directory.

This makes importing specific items from sub-modules awkward, since you need to write `import ... from 'tsdv-joi/dist/constraints/any'`. 

# Proposed solution
We copy package.json, README.md, and any other files to be published, into `dist` (or some other publishing directory alongside the generated JS files), and publish from _that_ directory instead of the project root.

**Comment by codeandcats** [comment]
Good idea copying package.json, etc to dist folder and publishing from there - much prefer this to building into the root and polluting that space with generated files. 👍

**Comment by laurence-myers** [comment]
Addressed by 468c210e295b1b71f7d1433766a70db6aee9293c, more work required on prepublish/postpublish steps from the project root vs the publish directory.

**Comment by laurence-myers** [comment]
Fixed in [v0.0.9](https://github.com/laurence-myers/tsdv-joi/tree/v0.0.9)
