### ISSUE TITLE
Create a logo to use for org and README

### ISSUE THREAD

**Issue by codeandcats** [joiful-ts/joiful#55]
A logo just adds a little bit of extra polish.

**Comment by laurence-myers** [comment]
I'm picturing an "@" with googly eyes and a joyous smile. Maybe with a speech bubble saying, "It looks like you're trying to validate an object! Would you like help with that?" 😅 

(The "@" represents the decorators.)

**Comment by laurence-myers** [comment]
Looks like we have a logo. We can come back to the googly eyes another time 😉
