### ISSUE TITLE
WhenOptions is not generic

### ISSUE THREAD

**Issue by codeandcats** [joiful-ts/joiful#8]
In later versions of `@types/joi` `WhenOptions` is no longer generic. So if the consuming application is using the latest version of `joi` then it will have the following build error:

```
node_modules/tsdv-joi/dist/constraints/any.d.ts(85,56): error TS2315: Type 'WhenOptions' is not generic.
```

I see a few possible solutions:
- (a) Depend on the specific versions of `joi` and `@types/joi` as [peer-dependencies](https://nodejs.org/en/blog/npm/peer-dependencies)
- (b) Update to the latest version of `joi` and `@types/joi`
- (c) Both of the above?

**Comment by laurence-myers** [comment]
`joi` and `types/joi` are already defined as peer dependencies:
```
"@types/joi": "^10.4.1",
"joi": "^10.6.0"
````
It's possible that `@types/joi` needs to use an exact version. I remember reading versioning guidelines for DefinitelyTyped that did not follow semantic versioning (e.g. the major version references the version of the library being typed, not breaking changes), so breaking changes can be introduced in minor/patch versions.

**Comment by codeandcats** [comment]
Ah sorry you're right re peer dependencies.

Hmm yeah looks like `WhenOptions` is defined as a generic type in `@types/joi` up until v10.4.3 which is technically a breaking change for a TS application. But yeah as you say, its tricky when type library authors are trying to match the major version normally reserved for breaking changes with the major version of the actual library, thus breaking semantic versioning. 🤔

Could you have `tsdv-joi` state it depends on an exact version (down to the patch) of `@types-joi`?

**Comment by laurence-myers** [comment]
Yeah, I think that makes sense. I haven't been able to think of a good way to allow using different versions of Joi, so maybe tsdv-joi just locks it down to a specific version. Which means it may as well include the library as a normal dependency, rather than a peer dependency.

**Comment by codeandcats** [comment]
Yeah, that's a good idea about having it as a normal dependency.

I mean if the developer is using `tsdv-joi` for validation they probably(?) don't wont also be using `joi` directly in their application so I'd guess its unlikely they'll have two versions of `joi` installed and mixing usage of the two.

Related question: Do you think TypeScript libraries should include typings for libraries they depend on as normal dependencies or dev dependencies? e.g. In this instance, should `@types/joi` be a normal dependency or a dev dependency? I'm not sure but I'm thinking normal?

**Comment by laurence-myers** [comment]
For tsdv-joi, I had to make it a normal dependency, because the types exported from tsdv-joi reference types exported from @types/joi. (Schemas, validation results)

For other @types packages only used internally, they should be fine as dev dependencies.

**Comment by laurence-myers** [comment]
@codeandcats It's actually likely that a consuming app will require `joi` as well. To make use of array validation, you can use the `@Items()` decorator, which accepts a Joi schema. To define that schema, you need to use `joi`.

**Comment by codeandcats** [comment]
Closing because new api does not support `when` decorator yet.
