### ISSUE TITLE
Upgrade to Joi v16

### ISSUE THREAD

**Issue by codeandcats** [joiful-ts/joiful#85]
Release notes and breaking changes: https://github.com/hapijs/joi/issues/2037

**Comment by gregory-latinier** [comment]
Hi,
Do you plan to upgrade to Joi v17 and skip the v16 ?

**Comment by codeandcats** [comment]
Hi Greg,

I’m a little time poor at the moment so I don’t have any immediate plans to upgrade to latest Joi.

That said, if you would like to have a crack at it, we currently have 100% test coverage and would welcome a PR. 🙂

**Comment by glen-84** [comment]
Closed by #166 (?).

**Comment by laurence-myers** [comment]
This was addressed in v3.0.0.
