### ISSUE TITLE
Nested validation improvement

### ISSUE THREAD

**Issue by fider-apptimia** [joiful-ts/joiful#93]
**Feature question:**

Hi, I wonder if it is **technically possible** to allow placing sub-properties validators inside class instead of defining new class:
```js
class Config {

  @jf.object().required()
  db: {

    @jf.object().required()
    credentials: {

      @jf.string().required()
      type: string,

      @jf.object().optional()
      userAndPass?: {
         @jf.string().required()
         user: string,
      }
    }
  }
}
```

??

**Comment by laurence-myers** [comment]
Unfortunately not.

In TypeScript, interfaces (and type literals and type aliases) only exist at compile time. Decorators are a runtime feature, they're just functions really. Classes are available at both runtime and compile time. This is why joiful uses classes - it allows us to specify the object structure for compile time validation, and apply decorators to the object properties for runtime validation.

There are other libraries that might provide a more fluent schema definition, e.g. https://github.com/TCMiranda/joi-extract-type - but they don't use decorators.

**Comment by fider-apptimia** [comment]
Thanks for quick reply and link. BR, Wojtek
